/**
 * AuditService - Business logic for audit management.
 *
 * Key changes in this version:
 * - createAudit() now accepts and stores the full templateQuestions at creation time.
 * - deleteAudit() is now a soft-delete (sets deletedAt) with cascade to TechniqueEntries.
 * - All find queries filter out soft-deleted records.
 * - guidedStep management: advanceStep(), goBackStep(), skipStep().
 */

import { GUIDED_STEPS } from '../models/Audit.js';

export class AuditService {
  constructor(auditRepository, techniqueRepository, songRepository) {
    if (!auditRepository) {
      throw new Error('AuditService requires an audit repository');
    }
    this.auditRepository = auditRepository;
    this.techniqueRepository = techniqueRepository;
    this.songRepository = songRepository;
  }

  // ─── Create ──────────────────────────────────────────────────────────────

  /**
   * Create a new audit.
   * The templateQuestions, templateVersion, modelUsed, and promptVersion
   * should be pre-generated by the route handler and passed in here.
   *
   * @param {Object} auditData
   * @returns {Promise<Object>} Created audit
   */
  async createAudit(auditData) {
    const {
      songId,
      userId,
      lensSelection,
      workflowType = 'quick',
      templateQuestions,
      templateVersion,
      modelUsed,
      promptVersion,
      responses,
    } = auditData;

    if (!songId || !userId || !lensSelection || !Array.isArray(lensSelection)) {
      throw new Error('Missing required fields or invalid lensSelection');
    }
    if (lensSelection.length === 0) {
      throw new Error('At least one lens must be selected');
    }

    // Verify song exists and belongs to user
    if (this.songRepository) {
      const song = await this.songRepository.findOne({ _id: songId, userId, deletedAt: null });
      if (!song) throw new Error('Song not found');
    }

    // Build guided steps for guided workflow
    const guidedSteps =
      workflowType === 'guided'
        ? GUIDED_STEPS.map((s) => ({
            stepNumber: s.stepNumber,
            name: s.name,
            instructions: s.instructions,
            status: s.stepNumber === 1 ? 'active' : 'pending',
            notes: '',
            skipped: false,
          }))
        : [];

    const audit = await this.auditRepository.create({
      songId,
      userId,
      lensSelection,
      workflowType,
      templateQuestions: templateQuestions || null,
      templateVersion: templateVersion || null,
      modelUsed: modelUsed || null,
      promptVersion: promptVersion || 'v1',
      responses: responses || {},
      bookmarks: [],
      techniques: [],
      guidedSteps,
      status: 'draft',
      deletedAt: null,
      createdAt: new Date(),
    });

    return audit;
  }

  // ─── Read ─────────────────────────────────────────────────────────────────

  /**
   * Fetch the song context (the song document) for an audit creation request.
   * Returns null if the song is missing, soft-deleted, or does not belong to the user.
   * Public method so route handlers don't have to reach into the repository.
   *
   * @param {string} songId
   * @param {string} userId
   * @returns {Promise<Object|null>}
   */
  async getSongContext(songId, userId) {
    if (!this.songRepository) return null;
    try {
      return await this.songRepository.findOne({ _id: songId, userId, deletedAt: null });
    } catch (err) {
      console.warn('[AuditService] getSongContext failed:', err.message);
      return null;
    }
  }

  async getAudit(auditId, userId) {
    const audit = await this.auditRepository.findById(auditId);
    if (!audit || audit.deletedAt) return null;
    // toString() handles ObjectId comparison
    if (audit.userId.toString() !== userId.toString()) return null;
    return audit;
  }

  async getAuditsForSong(songId, userId) {
    if (this.songRepository) {
      const song = await this.songRepository.findOne({ _id: songId, userId, deletedAt: null });
      if (!song) return [];
    }
    return this.auditRepository.find(
      { songId, userId, deletedAt: null },
      { sort: { createdAt: -1 } }
    );
  }

  async getUserAudits(userId) {
    return this.auditRepository.find(
      { userId, deletedAt: null },
      { sort: { createdAt: -1 } }
    );
  }

  // ─── Update ───────────────────────────────────────────────────────────────

  async updateAudit(auditId, userId, updates) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const allowed = ['responses', 'bookmarks', 'techniques', 'status', 'title', 'guidedSteps'];
    const sanitized = {};
    for (const key of allowed) {
      if (updates[key] !== undefined) sanitized[key] = updates[key];
    }

    // Auto-set completedAt when status changes to completed
    if (sanitized.status === 'completed' && !audit.completedAt) {
      sanitized.completedAt = new Date();
    }

    return this.auditRepository.updateById(auditId, {
      ...sanitized,
      updatedAt: new Date(),
    });
  }

  async updateResponses(auditId, userId, responses) {
    return this.updateAudit(auditId, userId, { responses });
  }

  async addBookmark(auditId, userId, bookmark) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const ts = Number(bookmark.timestampSeconds ?? bookmark.timestamp ?? 0);
    const newBookmark = {
      timestampSeconds: Math.max(0, ts),
      label: bookmark.label || '',
      note: bookmark.note || '',
      lens: bookmark.lens || null,
      createdAt: new Date(),
    };

    const bookmarks = [...(audit.bookmarks || []), newBookmark];
    // Sort by timestamp ascending
    bookmarks.sort((a, b) => a.timestampSeconds - b.timestampSeconds);

    return this.auditRepository.updateById(auditId, { bookmarks, updatedAt: new Date() });
  }

  async updateBookmark(auditId, userId, bookmarkId, updates) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const bookmarks = (audit.bookmarks || []).map((b) => {
      const id = b._id?.toString() ?? b.id;
      if (id !== bookmarkId) return b;
      return {
        ...b,
        label: updates.label ?? b.label,
        note: updates.note ?? b.note,
        lens: updates.lens !== undefined ? updates.lens : b.lens,
      };
    });

    return this.auditRepository.updateById(auditId, { bookmarks, updatedAt: new Date() });
  }

  async deleteBookmark(auditId, userId, bookmarkId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const bookmarks = (audit.bookmarks || []).filter((b) => {
      const id = b._id?.toString() ?? b.id;
      return id !== bookmarkId;
    });

    if (bookmarks.length === (audit.bookmarks || []).length) {
      throw new Error('Bookmark not found');
    }

    return this.auditRepository.updateById(auditId, { bookmarks, updatedAt: new Date() });
  }

  async logTechnique(auditId, userId, technique) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    if (this.techniqueRepository) {
      return this.techniqueRepository.create({
        auditId,
        userId,
        songId: audit.songId,
        techniqueName: technique.techniqueName || '',
        description: technique.description,
        lens: technique.lens || technique.category,
        exampleTimestamp: technique.exampleTimestamp ?? technique.sourceTimestamp,
        tags: technique.tags || [],
        notes: technique.notes,
        artist: technique.artist,
        confidence: technique.confidence,
        nextAction: technique.nextAction || null,
        deletedAt: null,
        createdAt: new Date(),
      });
    }

    // Fallback: embed directly in audit
    const techniques = [...(audit.techniques || []), technique];
    return this.auditRepository.updateById(auditId, { techniques, updatedAt: new Date() });
  }

  // ─── Guided step management ────────────────────────────────────────────────

  async advanceStep(auditId, userId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');
    if (audit.workflowType !== 'guided') throw new Error('Not a guided audit');

    const steps = [...(audit.guidedSteps || [])];
    const activeIdx = steps.findIndex((s) => s.status === 'active');
    if (activeIdx === -1) throw new Error('No active step found');

    steps[activeIdx] = { ...steps[activeIdx], status: 'complete', completedAt: new Date() };

    // Find next non-skipped pending step
    let nextIdx = activeIdx + 1;
    while (nextIdx < steps.length && steps[nextIdx].status === 'skipped') nextIdx++;
    if (nextIdx < steps.length) {
      steps[nextIdx] = { ...steps[nextIdx], status: 'active', startedAt: new Date() };
    }

    return this.auditRepository.updateById(auditId, { guidedSteps: steps, updatedAt: new Date() });
  }

  async goBackStep(auditId, userId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const steps = [...(audit.guidedSteps || [])];
    const activeIdx = steps.findIndex((s) => s.status === 'active');
    if (activeIdx <= 0) throw new Error('Already at first step');

    steps[activeIdx] = { ...steps[activeIdx], status: 'pending', startedAt: undefined };

    let prevIdx = activeIdx - 1;
    while (prevIdx > 0 && steps[prevIdx].status === 'skipped') prevIdx--;
    steps[prevIdx] = { ...steps[prevIdx], status: 'active', completedAt: undefined, startedAt: new Date() };

    return this.auditRepository.updateById(auditId, { guidedSteps: steps, updatedAt: new Date() });
  }

  async skipStep(auditId, userId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    const steps = [...(audit.guidedSteps || [])];
    const activeIdx = steps.findIndex((s) => s.status === 'active');
    if (activeIdx === -1) throw new Error('No active step to skip');

    steps[activeIdx] = { ...steps[activeIdx], status: 'skipped', skipped: true };

    let nextIdx = activeIdx + 1;
    while (nextIdx < steps.length && steps[nextIdx].status === 'skipped') nextIdx++;
    if (nextIdx < steps.length) {
      steps[nextIdx] = { ...steps[nextIdx], status: 'active', startedAt: new Date() };
    }

    return this.auditRepository.updateById(auditId, { guidedSteps: steps, updatedAt: new Date() });
  }

  // ─── Delete (soft) ────────────────────────────────────────────────────────

  /**
   * Preview what would be deleted along with an audit.
   * @returns {{ techniqueCount: number }}
   */
  async getDeletePreview(auditId, userId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) throw new Error('Audit not found');

    let techniqueCount = 0;
    if (this.techniqueRepository) {
      techniqueCount = await this.techniqueRepository.count({ auditId, deletedAt: null });
    }
    return { techniqueCount };
  }

  /**
   * Soft-delete an audit and cascade to linked TechniqueEntries.
   */
  async deleteAudit(auditId, userId) {
    const audit = await this.getAudit(auditId, userId);
    if (!audit) return false;

    const now = new Date();

    // Soft-delete all technique entries linked to this audit
    if (this.techniqueRepository) {
      const techniques = await this.techniqueRepository.find({ auditId, deletedAt: null });
      for (const t of techniques) {
        await this.techniqueRepository.updateById(t._id, { deletedAt: now });
      }
    }

    await this.auditRepository.updateById(auditId, { deletedAt: now });
    return true;
  }

  // ─── Stats ────────────────────────────────────────────────────────────────

  async getStats(userId) {
    const audits = await this.auditRepository.find({ userId, deletedAt: null });
    const lensStats = {};
    audits.forEach((audit) => {
      (audit.lensSelection || []).forEach((lens) => {
        lensStats[lens] = (lensStats[lens] || 0) + 1;
      });
    });
    return {
      totalAudits: audits.length,
      completedAudits: audits.filter((a) => a.status === 'completed').length,
      lensStats,
    };
  }

  // ─── Trash / Archives ─────────────────────────────────────────────────────

  /**
   * Get all soft-deleted audits for a user whose parent song is active.
   */
  async getDeletedAudits(userId) {
    const audits = await this.auditRepository.find({ userId, deletedAt: { $ne: null } });
    const deletedAudits = audits.filter((a) => a.deletedAt !== null && a.deletedAt !== undefined);

    const results = [];
    for (const audit of deletedAudits) {
      if (this.songRepository) {
        const song = await this.songRepository.findById(audit.songId);
        if (song && !song.deletedAt) {
          // Attach populated song info
          audit.songId = song;
          results.push(audit);
        }
      } else {
        results.push(audit);
      }
    }

    return results.sort((a, b) => new Date(b.deletedAt) - new Date(a.deletedAt));
  }

  /**
   * Restore a soft-deleted audit and its techniques.
   */
  async restoreAudit(auditId, userId, techniqueRepository) {
    const audit = await this.auditRepository.findById(auditId);
    if (!audit || audit.userId.toString() !== userId.toString() || !audit.deletedAt) {
      return false;
    }

    if (this.songRepository) {
      const song = await this.songRepository.findById(audit.songId);
      if (!song || song.deletedAt) {
        throw new Error('Cannot restore audit because its parent song is deleted. Restore the song first.');
      }
    }

    const techRepo = techniqueRepository || this.techniqueRepository;
    if (techRepo) {
      const allTechs = await techRepo.find({ auditId, deletedAt: { $ne: null } });
      const deletedTechs = allTechs.filter((t) => t.deletedAt !== null && t.deletedAt !== undefined);
      for (const t of deletedTechs) {
        await techRepo.updateById(t._id, { deletedAt: null });
      }
    }

    await this.auditRepository.updateById(auditId, { deletedAt: null });
    return true;
  }

  /**
   * Permanently delete an audit and its techniques.
   */
  async purgeAudit(auditId, userId, techniqueRepository) {
    const audit = await this.auditRepository.findById(auditId);
    if (!audit || audit.userId.toString() !== userId.toString()) {
      return false;
    }

    const techRepo = techniqueRepository || this.techniqueRepository;
    if (techRepo) {
      await techRepo.deleteMany({ auditId });
    }

    await this.auditRepository.deleteById(auditId);
    return true;
  }
}
